# Generated by Django 4.2 on 2023-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=3)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weights', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
