# Generated by Django 4.2 on 2023-04-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listoffood',
            name='weights',
        ),
    ]
