# Generated by Django 4.2 on 2023-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_listoffood_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listoffood',
            name='carbs',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='listoffood',
            name='fats',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='listoffood',
            name='protein',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
