# Generated by Django 4.2 on 2023-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_listoffood_carbs_alter_listoffood_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listoffood',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
        migrations.AlterField(
            model_name='listoffood',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
        migrations.AlterField(
            model_name='listoffood',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
